package com.manishjandu.bcontacts.utils

object Constants {
    const val FRAGMENT_SELECT_MULTIPLE_CONTACT_REQUEST_KEY=
        "FRAGMENT_SELECT_MULTIPLE_CONTACT_REQUEST_KEY"
    const val CONTACT_SELECTED = "CONTACT_SELECTED"
    const val MULTIPLE_USER_MESSAGE_REQUEST_CODE = 100000
    const val BIRTHDAY_REQUEST_CODE = 500000
}